### ISSUE TITLE
1000-sans.badssl.com & 10000-sans.badssl.com

### ISSUE THREAD

**Issue by marumari** [lgarron/badssl.com#105]
Two sites, one with 1000 subjectAltNames, and one with 10000 subjectAltNames.  The prior seems to work with everything, the latter breaks Firefox and Chrome.  Safari works with 10000 hosts, but looking at the cert causes some impressive beach balls.

@lgarron, if you have a better host name idea, I'd be happy to change it.  It's otherwise mostly ready to go.

**Comment by lgarron** [comment]
`huge-san.badssl.com`
`huger-san.badssl.com`
?

:-P

**Comment by Hoverbear** [comment]
These names are fun because it's like death by a thousand cuts!

**Comment by lgarron** [comment]
> These names are fun because it's like death by a thousand cuts!

I supposed they're more directly descriptive. However:
- `hosts` on its own doesn't indicate that this is about the cert – particularly, the SAN. ("Is this subdomain hosted on a thousand hosts?")
- All other subdomains use digits instead of words to refer to numbers (e.g. `1000` instead of `thousand`).

I'm happy to compromise on something that addresses those, though.

**Comment by marumari** [comment]
1000-sans and 10000-sans seems fine to me.

**Comment by marumari** [comment]
Or death-by-1000-sans.   :)

**Comment by Hoverbear** [comment]
Sounds like a sweet font...

**Comment by marumari** [comment]
Completed in #108.
