### ISSUE TITLE
SHA-1 site lacks sufficient detail

### ISSUE THREAD

**Issue by marumari** [lgarron/badssl.com#12]
The SHA-1 site should probably say SHA-1 2015 *and* use a SHA-1 certificate that expires in 2015, especially when the SHA-1 2016 and SHA-1 2017 sites go live.

Oddly enough, the official sha1-2016.badssl.com does not generate any certificate warnings in Chrome, but the one that uses my self-signed root *does* generate a warning.  I feel like my behavior is the correct before, and the one that we should be demonstrating, and that the official site is incorrect.  I'm not sure why the official sha1-2016.badssl.com doesn't generate a warning in chrome, though.

Is it because its key is pinned or something?

**Comment by marumari** [comment]
Looks like it was just a Chrome bug:

https://code.google.com/p/chromium/issues/detail?id=483874&thanks=483874&ts=1430613035

But I still think the SHA-1 site should specifically note 2015/2016/2017.

**Comment by lgarron** [comment]
[sha1.badssl.com](https://sha1.badssl.com/) uses a cert expiring in 2016. ;-)

It originally looked like I'd be able to get a SHA-1 cert expiring in 2017 easily. The plan was to use `sha1-2016.badssl.com` and `sha1-2017.badssl.com` explicitly, and to redirect `sha1.badssl.com` to one of them.

`sha1.badssl.com` has been in a "temporary" state that's been waiting on someone at Comodo for a few weeks now. ;-)

Until we're sure we'll have a 2017 cert (I'll believe it when I have it in hand), I think the best is to add an informational message to `sha1.badssl.com` (similar to `preloaded-hsts.badssl.com`). Eventually, I'd like all the domains to explain their purpose, anyhow.

> Looks like it was just a Chrome bug:

Yeah, I had a fun day where I was debugging the SHA-1 warning, and couldn't tell if it was caused by Finch. :-/

**Comment by marumari** [comment]
As I was the one who submitted that Chrome bug, I truly hope I didn't create an entire days worth of work for you.  >_<

Also, April Corporation Certificate Authority is issuing 2017 SHA-1 certificates at this very moment.  Just send them a crisp new $500 bill and they'll sign whatever you want.  *grins*

**Comment by lgarron** [comment]
> As I was the one who submitted that Chrome bug, I truly hope I didn't create an entire days worth of work for you. >_<

Nah, that was [here](https://crbug.com/469853#c22).
Thanks for filing a bug, though. In this case, your behaviour was unexpected, and it's usually good to file a bug for that.

> Also, April Corporation Certificate Authority is issuing 2017 SHA-1 certificates at this very moment. Just send them a crisp new $500 bill and they'll sign whatever you want. grins

ACCA sounds like a cool Swedish parody rock band. I like to get my certs from SSCA ("Super-Secure Certificate Authority"). :-P

(Also, $500 bills have been out of print for 80 years?)

**Comment by marumari** [comment]
> (Also, $500 bills have been out of print for 80 years?)

That's why they only want crisp new ones!  :D

**Comment by lgarron** [comment]
I think we're good as of 398d17a60b4e64ee6791056a72145e4951b10c39.
