### ISSUE TITLE
cert-generator.sh fails with an opaque error if certs are already generated.

### ISSUE THREAD

**Issue by lgarron** [lgarron/badssl.com#41]
In particular, if you run `cert-generator.sh` on a fresh clone, it will print:

    Generating BadSSL Certificate Signing Request
    
    Signing BadSSL Default Certificate
    Signature ok
    subject=/C=US/ST=California/L=San Francisco/O=BadSSL/CN=*.badssl.com
    Getting CA Private Key
    Error opening CA Private Key ../self-signed/badssl-intermediate.key
    139949868869280:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('../self-signed/badssl-intermediate.key','r')
    139949868869280:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
    unable to load CA Private Key

@marumari, would you mind handling this? A simple solution would be to check if `self-signed/` contains any certs, and exit an error message.
A nicer solution might be to ask and offer to overwrite the old certs.

**Comment by marumari** [comment]
Sure, I'll take care of it.  :)

**Comment by marumari** [comment]
FYI, the badssl intermediate should have been checked in the entire time (along with the root key).  I'm going to spend some time doing major cleanup on the cert generator; it was one of those dirty quick shell scripts that I made to get going on development in the first place.  :)

**Comment by lgarron** [comment]
> FYI, the badssl intermediate should have been checked in the entire time (along with the root key). I'm going to spend some time doing major cleanup on the cert generator; it was one of those dirty quick shell scripts that I made to get going on development in the first place. :)

:-D

While we're on the topic, a good feature would probably to be able to regenerate everything while keeping the root CA.

**Comment by marumari** [comment]
Right now it keeps the keys around (root, intermediate, and EE) and generates all the certificates anew every time.  There’s no reason why it couldn’t regenerate the intermediate and EE keys every time, but obviously regenerating the root is a giant pita.

We have two plausible options:

1) make install (or some hypothetical make roots or make keys) deletes the keys in self-signed: this will cause cert-generator.sh to generate all new keys and certs

2) have cert-generator.sh prompt upon execution, for example:

“Would you like to regenerate the root for badssl.com?  It is recommended you do this for each new installation, for security purposes.  [Y/N]”

And choosing y or Y will delete the keys in self-signed, causing everything to be regenerated.

Personally, I’m leaning a bit towards the former option.  Not just because it’s less work for me — I run cert-generator.sh constantly — but also because I imagine most users will simply stop at make install, if that’s what README.md tells them to do.

**Comment by lgarron** [comment]
> 1) make install (or some hypothetical make roots or make keys) deletes the keys in self-signed: this will cause cert-generator.sh to generate all new keys and certs

Yeah, I think it makes sense to do this without prompting.

If for some crazy reason lots of people need to use this project and regenerate certs without losing the old ones, we can consider storing old ones in a backup folder.

One idea I kind of like would be to throw away the root/intermediate keys after signing certs (even better: only keep it in RAM before doing so), so that no one can sign any more certs. Until name constraints become commonly implemented (i.e. never), this is the best assurance that the test root cert won't be used for domains it wasn't intended for.
My main concern is that this requires updating imported test root certs, which is something I'm wary of automating.

**Comment by marumari** [comment]
If we add a make keys option, should we simply remove the keys and certs that are there in the repository currently, forcing everybody to generate them on first install?  Then we don't need to worry about throwing away the root/intermediate keys, since they can't sign anything of importance.

**Comment by lgarron** [comment]
Yeah, that actually sounds sensible.
It will make it annoying to test in an environment where you can't run `openssl` – but if you don't know enough to work around it on another server, then arguably you shouldn't be qualified to run this.

**Comment by marumari** [comment]
I'm still working on this thing, but it's a surprisingly complicated one.  It's the kind of pull request that'll make you groan and curse my name.  :)

**Comment by marumari** [comment]
The commit for this is in, in #55!  Take a look, and if you like the way its handled, I'll close this ticket.
